INSERT INTO api.taxis (id, plate)
VALUES (7249, 'CNCJ-2997')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (10133, 'PAOF-6727')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2210, 'FGMG-3071')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1065, 'GHDN-9291')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7956, 'CCKF-1601')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (252, 'LAHG-7611')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9557, 'BOIG-0354')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4485, 'LLEL-9271')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6418, 'GHGH-1458')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8825, 'HBEE-6337')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (974, 'FNDF-2678')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8935, 'GAJG-2446')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6772, 'NOCB-3788')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6680, 'MCCI-5437')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4831, 'FHCI-2846')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3300, 'NBAC-4573')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3859, 'GPGM-7365')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7938, 'HLBO-2375')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1999, 'MOCP-7556')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7215, 'JJNC-1645')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6782, 'KOFG-2986')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4055, 'KPKO-3451')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3560, 'GJCC-2787')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5561, 'FKOH-3490')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7813, 'FFGI-2329')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8716, 'EONJ-3377')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (10293, 'POOD-6790')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4028, 'HNHM-3476')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3282, 'MDDB-5497')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8311, 'GNGM-2252')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9408, 'CHGM-2476')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3510, 'FEHJ-7325')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7300, 'HHJP-8573')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7088, 'HDBL-4695')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (296, 'CGEF-7101')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6598, 'FHLB-7962')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4910, 'GDEE-7052')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6642, 'DKOK-3814')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3335, 'EHMB-5718')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9275, 'ENPB-7532')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9098, 'MIHI-5177')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4105, 'MLGC-5558')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2816, 'AFOI-1144')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7027, 'OGHL-0787')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1364, 'EGFM-5153')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (655, 'NOGG-5935')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9440, 'FDCH-3572')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6163, 'PEPP-9872')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5170, 'FCBN-3511')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (167, 'IIJB-4867')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9916, 'BLDG-3162')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8604, 'HOMH-4581')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8300, 'EDOF-2862')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8305, 'GIBC-2378')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (71, 'CLLD-1805')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7218, 'MNBE-4846')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2761, 'CFBG-2755')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (624, 'FKLI-9441')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (626, 'ECFG-9397')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4728, 'DABK-9431')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4145, 'LGHO-2055')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9452, 'KEBK-7570')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6374, 'KCGK-4346')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8484, 'FHEE-8646')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8491, 'BNJE-8175')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8751, 'GMEC-3019')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4056, 'CIKI-8122')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (280, 'IHIH-1812')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6286, 'MLHK-7222')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2886, 'AIGG-5536')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2925, 'BADO-1416')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3492, 'OKCA-5223')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7131, 'OKAL-8398')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1139, 'MFEF-8699')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9271, 'JDOL-5035')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4416, 'KHIE-6756')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2270, 'GJGE-8317')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2522, 'LGBJ-0156')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9406, 'EIGN-5732')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2542, 'DOHO-6151')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2230, 'LOFJ-3431')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4787, 'NGKN-4357')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7493, 'MOJF-6958')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1963, 'NBNI-1458')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (15, 'FNHK-3772')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9328, 'EHBL-7645')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6118, 'IBNE-0418')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5210, 'IPGK-3957')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9061, 'NPGE-7240')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (56, 'JIMF-2287')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9678, 'FLPG-1136')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7169, 'CKEH-6725')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2183, 'MKMJ-7264')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6790, 'MGMA-6670')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6129, 'FLGH-8619')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8466, 'GGHB-2669')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2211, 'FHID-7265')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4449, 'JGIE-0333')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6700, 'BLMO-4997')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2112, 'GHNJ-1555')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7934, 'PCKL-3328')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5224, 'KMDK-1502')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7150, 'DNCJ-7132')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3979, 'IEMK-7327')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (10206, 'INHN-2688')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (923, 'IBIJ-5577')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8362, 'GPGD-1746')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3082, 'BDFM-5551')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8251, 'GOAJ-6841')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8320, 'OOMH-5539')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (10207, 'JLDK-4535')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2179, 'MKFF-1845')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7534, 'MICH-4553')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8433, 'IGMB-9195')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8585, 'MDEF-7585')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (376, 'DDNG-0487')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (10247, 'OBEF-5861')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (515, 'EHCE-5183')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7613, 'FCKB-6558')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2783, 'LIEL-8257')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4453, 'DNCM-7790')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6298, 'DCFM-2125')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9654, 'ENKO-4271')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2717, 'LBOK-2444')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8011, 'FJEC-3215')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9836, 'FHGJ-5518')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5256, 'HMMN-0507')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5610, 'KOGN-4837')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (165, 'HKNN-8042')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5803, 'HNMB-4988')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9451, 'MLMM-3869')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5838, 'MBND-8204')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (21, 'NNEL-8793')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6247, 'KMGB-7305')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (570, 'AMGF-6934')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5270, 'BDLP-4643')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3942, 'JLBH-4071')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8776, 'MDDJ-5215')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1049, 'BHNL-4225')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9513, 'FNHL-5802')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6058, 'JBKB-1428')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7779, 'KGHD-5576')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6056, 'BJFI-7501')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8869, 'HINB-4821')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (609, 'PNCB-3390')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4242, 'LGEF-9081')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9300, 'KEJH-7652')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7397, 'DHFJ-3563')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8733, 'GMGM-1378')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3029, 'MBDM-1187')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9643, 'GHDD-1743')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9298, 'EMOJ-3697')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1806, 'HGIJ-7345')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7834, 'GKGI-7231')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2153, 'KHGM-2815')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6899, 'KACP-6171')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7217, 'IELF-5280')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2692, 'NEIJ-5872')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6768, 'FCPJ-0116')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8230, 'CDKL-3488')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6643, 'KJDE-7135')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8410, 'GNDO-6910')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8150, 'BBJC-1672')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5540, 'OHAE-8815')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6031, 'HFND-4178')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3812, 'AAML-9871')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2677, 'PGDC-1949')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3458, 'GGDE-3387')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9238, 'LLOD-8718')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9018, 'MOJL-7377')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8377, 'LPOM-8373')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7219, 'LPJA-3471')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7189, 'DKFB-4482')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2351, 'FIPC-8785')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (108, 'LNGK-1108')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8974, 'CKNH-1553')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7646, 'FOFM-3206')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3379, 'MPNJ-7725')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1475, 'KJDM-6267')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (1017, 'MIFO-1824')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9217, 'MJDD-8286')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6737, 'DLEP-5452')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2719, 'BKAM-8657')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3663, 'DOKF-7876')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7716, 'IAMG-2604')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3572, 'GFHP-7928')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7302, 'KDJI-8221')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5240, 'COIO-8354')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (10026, 'FFNJ-9813')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2353, 'DIFO-4571')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (6841, 'MGKK-5876')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (8715, 'NFJM-6129')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (5370, 'HBJH-8671')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (804, 'CDBJ-7875')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (4397, 'EGDN-3052')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7262, 'FDAP-3298')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (3900, 'EIED-2133')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (2611, 'EGOA-2654')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (9357, 'BLFH-6860')
ON CONFLICT (id) DO NOTHING;
INSERT INTO api.taxis (id, plate)
VALUES (7957, 'BAJW-7971')
ON CONFLICT (id) DO NOTHING;